config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#index'
  get 'about', to: 'pages#about'
  get 'root', to: 'pages#index'
  get '/login', to: 'pages#index'
  post '/login', to: 'pages#index'

  resources :articles do
    resources :comments, only: :create
    resource :likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  resources :users, only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 1500 }
  mount_uploader :image, ImageUploader

  belongs_to :user
  has_many :comments
  has_many :likes, dependent: :destroy

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

  def self.search(search)
    if search
      Article.where(['title LIKE(?)', "%#{search}%"])
    else
      Article.all
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :article, counter_cache: :likes_count

  validates :user_id, presence: true
  validates :article_id, presence: true
  validates_uniqueness_of :article_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, uniqueness: true
  has_many :articles
  has_many :comments
  has_many :likes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :move_to_index, except: [:index, :show, :search]

  def index
    @articles = Article.includes(:user).order("created_at DESC")
  end

  def create
    @article = Article.new(article_params)
    if @article.save
     flash[:notice] = "記事が投稿されました"
     redirect_to article_path(@article)
    else
     render 'new'
    end
  end

  def new
    @article = Article.new
  end

  def show
    @comment = Comment.new
    @comments = @article.comments.includes(:user)
    @likes_count = Like.where(article_id: @article.id).count
  end

  def edit
    unless @article.user_id == current_user.id
      redirect_to root_path
    end
  end

  def update
    if @article.update(article_params)
     flash[:notice] = "記事が更新されました"
     redirect_to article_path(@article)
    else
     flash[:notice] = "記事の更新ができませんでした"
     render 'edit'
    end
  end

  def destroy
    @article.destroy
    flash[:notice] = "記事が削除されました"
    redirect_to articles_path
   end

  def search
    @articles = Article.search(params[:keyword]).order("created_at DESC")
  end

  private
  def article_params
    params.require(:article).permit(:title, :description, :image).merge(user_id: current_user.id)
  end

  def set_article
    @article = Article.find(params[:id])
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/articles/#{comment.article.id}"
  end
  
  private
  def comment_params
    params.require(:comment).permit(:description).merge(user_id: current_user.id, article_id: params[:article_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_article

  def create
    like = current_user.likes.build(article_id: params[:article_id])
    like.save
    @article = Article.find_by(id: @like.article_id)
    @like_count = Like.where(article_id: params[:article_id]).count
    render 'create.js.erb'
  end

  def destroy
    like = Like.find_by(article_id: params[:article_id], user_id: current_user.id)
    like.destroy
    @like_count = Like.where(article_id: params[:article_id]).count
    render 'destroy.js.erb'
  end

  def set_article
    @article = Article.find(params[:article_id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @articles = Article.includes(:user).order("created_at DESC").limit(5)
    # @articles = Article.includes(:article_images).order('created_at DESC')
    # @categories = Article.includes(:article_images).where(category_id:1..4).order('created_at DESC').limit(4).where.not(trading_status: 0)
  end

  def about
  end

end

  

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @name = user.name
    @articles = user.articles
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.haml
%header
= render('templates/header')
-# .header__middle
-#   = form_with(url: search_articles_path, local: true, method: :get, class: "search-form") do |f|
-#     = f.text_field :keyword, placeholder: "投稿を検索する", class: "search-input"
-#     = f.submit "検索", class: "search-btn"
.contents.row
  - @articles.each do |article|
    = render partial: "article", locals: { article: article }

app/views/articles/_form.html.haml
.NewArticle__erroer
  - if @article.errors.any?
    %h2 次のエラーにより、記事を保存できませんでした:
    %ul
      - @article.errors.full_messages.each do |msg|
        %li= msg

app/views/articles/edit.html.haml
%header
= render('templates/header')
.NewArticle
  .NewArticle__page
    記事の編集
  = render 'form'
  .NewArticle__form
  = form_with(model: @article, local: true) do |f|
    .FormBox
      .FormBox__label--normal
        = f.label :タイトル
      .FormBox__input--normal
        = f.text_field :title
      .FormBox__label--normal
        = f.label :本文
      .FormBox__input--normal
        = f.text_area :description, rows: 10
      .ImageLogo
        = image_tag(@article.image_url) if @article.image.present?
        = f.label :image, class: 'ImageLogo__image' do
          %br
          = icon('far', 'image', class: 'ImageLogo__icon')
          = f.file_field :image, class: 'file'
    .action
      = f.submit '更新する'
    .return
      = link_to '戻る', articles_path

= render "/pages/site_map"

app/views/articles/index.html.haml
%header
= render('templates/header')
.ArticleTop
  .ArticleTop__page
    記事一覧
    .ArticleTop__page__items
      .ArticleTop__page__items__newpost
        = link_to "新規投稿", new_article_path
      .ArticleTop__page__items__toppage
        = link_to 'トップページ', root_path
  .ArticleTop__contents
    .Contents
      - @articles.each do |article|
        .murata
          .murata__post
          投稿者
          = link_to article.user.name, user_path(article.user.id), method: :get
          .Content
            .Content__Image
              = link_to article_path(article.id) do
                = image_tag "#{article.image}"
            .Content__Title
              = link_to article.title , article_path(article.id), method: :get
            .Content__Description
              = link_to article.description , article_path(article.id), method: :get

= render "/pages/site_map"

app/views/articles/new.html.haml
%header
= render('templates/header')
.NewArticle
  .NewArticle__page
    新規投稿
  = render 'form'
  .NewArticle__form
    = form_for @article do |f|
      .FormBox
        .FormBox__label--normal
          = f.label :タイトル
        .FormBox__input--normal
          = f.text_field :title
        .FormBox__label--normal
          = f.label :本文
        .FormBox__input--normal
          = f.text_area :description, rows: 10
        .ImageLogo
          = f.label :image, class: 'ImageLogo__image' do
            = icon('far', 'image', class: 'ImageLogo__icon')
            = f.file_field :image, class: 'file'
      .action
        = f.submit '投稿する'
      .return
        = link_to '戻る', articles_path

= render "/pages/site_map"

app/views/articles/search.html.haml
%header
= render('templates/header')
.ArticleTop
  .ArticleTop__page
    = link_to '記事一覧', articles_path
  .ArticleTop__contents
    .Contents
      - @articles.each do |article|
        .murata
          .murata__post
          投稿者
          = link_to article.user.name, user_path(article.user.id), method: :get
          .Content
            .Content__Image
              = link_to article_path(article.id) do
                = image_tag "#{article.image}"
            .Content__Title
              = link_to article.title , article_path(article.id), method: :get
            .Content__Description
              = link_to article.description , article_path(article.id), method: :get

= render "/pages/site_map"

app/views/articles/show.html.haml
%header
= render('templates/header')
.Wrapper
  .ShowArticle
    .ShowArticle__detail
      .ShowArticle__detail__name
        = link_to @article.user.name, user_path(@article.user.id), method: :get
      .ShowArticle__detail__like
        %div{:id => "like-btn#{@article.id}"}
        = render partial: "likes/like", locals: { article: @article }
      .ShowArticle__detail__title
        #{@article.title}
      .ShowArticle__detail__description
        #{@article.description}
      .ShowArticle__detail__image
        = image_tag(@article.image_url) if @article.image.present?
    .ShowArticle__ShowReturn
    - if user_signed_in? && current_user.id == @article.user_id
      .ShowArticle__ShowReturn__Contents
        .ShowArticle__ShowReturn__Contents__edit
          = link_to '編集', edit_article_path(@article.id), method: :get
        .ShowArticle__ShowReturn__Contents__delete
          = link_to '削除', article_path(@article.id), method: :delete, data: {confirm: "本当に削除しますか?"}
        .ShowArticle__ShowReturn__Contents__return
          = link_to '戻る', articles_path

  - if current_user
    .Comments
      = form_with(model: [@article, @comment], local: true) do |f|
        .Comments__text
        %br
          =f.text_area :description, placeholder: "コメントする", row: "2"
        %br
          =f.submit "投稿する"
  - else
    ※※※ コメントの投稿には新規登録/ログインが必要です ※※※
  .Messages
    %h4 コメント一覧
    - if @comments
      - @comments.each do |comment|
        %p
          %strong
            = link_to comment.user.name, "/users/#{comment.user_id}"
            ：
          = comment.description

= render "/pages/site_map"

app/views/layouts/_notifications.html.haml
.Notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Trip Log
    %meta{charset: "utf-8"}
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application'
    %link{href: "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css", rel: "stylesheet", type: "text/css"}/
    %script{src: "https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"}
    %script{src: "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js", type: "text/javascript"}
    %link{:href => "https://use.fontawesome.com/releases/v5.6.4/css/all.css", :rel => "stylesheet"}/

  .body
    = render 'layouts/notifications'
    = yield

  .footer
    .footer__left
      = link_to image_tag("torilog.png", alt: "Rails logo", class: "torilog_Logo")
      ©️ 2020 Tori Log, Inc. All rights reserved
    .footer__right
      .footer__right__line
        .line-it-button{"data-color" => "default", "data-count" => "false", "data-lang" => "ja", "data-size" => "small", "data-type" => "share-b", "data-url" => "http://localhost:3000/users/sign_in", "data-ver" => "3", :style => "display: none;"}
        %script{:async => "async", :defer => "defer", :src => "https://d.line-scdn.net/r/web/social-plugin/js/thirdparty/loader.min.js"}
      .footer__right__facebook
        =link_to "https://www.facebook.com/share.php?u=http://localhost:3000/users/sign_in/" do
          %i.fab.fa-facebook-square
      .footer__right__twitter
        =link_to "http://twitter.com/share?url=#{request.url}/&text=旅の記録を楽しもう♪" do
          %i.fab.fa-twitter-square
          
            

      

app/views/likes/_like.html.haml
- if user_signed_in? && article.liked_by?(current_user)
  = link_to article_likes_path(article.id),  method: :delete, class: "like-btn-unlike" , remote: true do
    %i.fas.fa-heart
    = @likes_count
- else
  = link_to article_likes_path(article.id), method: :post, class: "like-btn" , remote: true do
    %i.fas.fa-heart
    = @likes_count

app/views/likes/create.js.erb
$('.like-btn_<%= @article.id %>').html("<%= j(render partial: 'likes/like' ) %>");

app/views/likes/destroy.js.erb
$('.like-btn-unlike_<%= @article.id %>').html("<%= j(render partial: 'likes/like' ) %>");

app/views/pages/_site_map.html.haml
.under-field
  %ul.under-field__term
    %li.under-field__term__content
      %h2.under-field__term__content__title Trip Logについて
      %ul.under-field__term__content__text
        %li
          %a(href="#") About Trip Log
        %li
          %a(href="#") 会社概要
        %li
          %a(href="#") アクセス
        %li
          %a(href="#") Trip Log利用規約
    %li.under-field__term__content
      %h2.under-field__term__content__title Trip Logを見る
      %ul.under-field__term__content__text
        %li
          %a(href="#") カテゴリー一覧
        %li
          %a(href="#") ランキング
        %li
          %a(href="#") この夏のオススメ
        %li
          %a(href="#") 注目の遊び方
    %li.under-field__term__content
      %h2.under-field__term__content__title ヘルプ＆ガイド
      %ul.under-field__term__content__text
        %li
          %a(href="#") Trip Logガイド
        %li
          %a(href="#") コミュニティ
        %li
          %a(href="#") お知らせ
        %li
          %a(href="#") お問い合わせ

app/views/pages/about.html.haml
%header
= render('templates/header')
.About
  .About__Contents
    .About__Contents__Content
    %h1 About Trip Log
    .About__Contents__ContentTwo
    = link_to 'トップページ', root_path
  .About__Body
    .About__Body__ParagraphLeft
    .About__Body__ParagraphRight
      .About__Body__ParagraphRight__FirstLine
        旅には新しい経験、出会いを与えてくれる。
        %br
          あなたの経験はあなたでしか語れないもの。
      .About__Body__ParagraphRight__SecondLine
        Trip Log
      .About__Body__ParagraphRight__ThirdLine
        人生の楽しみを記録して、新たな出会いを繋いでいく。
        %br
          生きることの楽しみを、人と繋がる喜びを、
          %br
            豊かな人生を後押しすること。
            %br
              さらなる喜びを求めて、あなたの旅路を記録しよう。
    

    -# .About__Contents__ContentTwo
    -# = link_to image_tag("vacation.jpg", alt: "about_trip_log", class: "travel", with: "2000", height: "1000")



= render "/pages/site_map"

app/views/pages/index.html.haml
%header
= render('templates/header')
%body
  %ul.slider
    %li
      = link_to image_tag("TopOne.jpg", alt: "Rails logo", class: "torilog_Logo")
    %li
      = link_to image_tag("TopTwo.jpg", alt: "Rails logo", class: "torilog_Logo")
    %li
      = link_to image_tag("TopThree.jpg", alt: "Rails logo", class: "torilog_Logo")
    %li
      = link_to image_tag("TopFour.jpg", alt: "Rails logo", class: "torilog_Logo")

.TopPage
  .TopPage__Contents
    .TopPage__Contents__content
      = link_to '記事一覧', articles_path
    - @articles.each do |article|
      .TopArticles
        .TopArticles__TopNews
          投稿者
          = link_to article.user.name, user_path(article.user.id), method: :get
          .TopPageContents
            .TopPageContents__Image
              = link_to article_path(article.id) do
                = image_tag "#{article.image}"
            .TopPageContents__Title
              = link_to article.title , article_path(article.id), method: :get
            .TopPageContents__Description
              = link_to article.description , article_path(article.id), method: :get

= render "site_map"

app/views/templates/_header.html.haml
.header
  .header__left
    = link_to image_tag("ToripLog.png", class: "Trip_Log_Logo"), |
  root_path       
  .header__middle
    = form_with url: search_articles_path, local: true, method: :get, class: "search-form" do |form|
      = form.text_field :keyword, placeholder: "投稿タイトルを検索する", class: "search-input"
      = form.submit "検索", class: "search-btn"
  .header__right
    .header__right__username
      = link_to current_user.name, "/users/#{current_user.id}"
      -# = current_user.name
      .upper-field__navigate
        .upper-field__navigate__left-side
          %ul.upper-field__navigate__left-side__item
            %li
              %i.fas.fa-th-large
              %ul
                = link_to 'About Trip-Log', about_path
                %li
                  = link_to 'トップページ', root_path
                %li
                  = link_to '記事一覧', articles_path
                %li
                  = link_to "新規投稿", new_article_path
                %li
                  = link_to "マイページ", "/users/#{current_user.id}"
                %li
                  = link_to 'アカウント編集', edit_user_registration_path
                %li
                  = link_to "ログアウト", destroy_user_session_path, method: :delete

app/views/users/edit.html.haml
.AccountPage
  .AccountPage__title
    %h2 Edit Account
    %h5 アカウントの編集
    = link_to "ログアウト", '#', class: 'Button'
    = link_to "トップページに戻る", :back, class: 'Button'
  .AccountPage__form
    = form_for(current_user) do |f|
      .FormField
        .FormField__label--normal
          = f.label :name
        .FormField__input--normal
          = f.text_field :name, autofocus: true
      .FormField
        .FormField__label--normal
          = f.label :email
        .FormField__input--normal
          = f.email_field :email
      = f.submit "Update", class: 'Button UserButton'

app/views/users/show.html.haml
%header
= render('templates/header')
.UserInfo
  .UserInfo__name
    = @name
    さんの投稿一覧
    .UserInfo__contents
      .Contents
        - @articles.each do |article|
          .MyPage
            .MyPage__Top
              投稿者
              .SubName
                = link_to article.user.name
              .SubItems
                - if user_signed_in? && current_user.id == article.user_id
                  .SubItems__edit
                    = link_to '編集', edit_article_path(article.id), method: :get
                  .SubItems__detail
                    = link_to '詳細', article_path(article.id), method: :get
                  .SubItems__delete
                    = link_to '削除', article_path(article.id), method: :delete, data: {confirm: "本当に削除しますか?"}
            
            .Content
              .Content__Image
                = link_to article_path(article.id) do
                  = image_tag "#{article.image}"
              .Content__Title
                = link_to article.title , article_path(article.id), method: :get
              .Content__Description
                = link_to article.description , article_path(article.id), method: :get
                
= render "/pages/site_map"
              
          